site_name: 6NdR

theme: 
  name: material
  language: fr
  logo: assets/images/bender-fourrure-3.png
  favicon: assets/images/bender-fourrure-3.ico
  features:
    - navigation.tabs
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Passer en mode sombre
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Passer en mode clair

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/6NdR
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julienlediagon
    - icon: material/email
      link: mailto:6ndr.contact@gmail.com

copyright: Copyright &copy; 2025 - 6NdR

nav:
  - Linux Handbook: 
      - Introduction: linux-handbook/introduction.md
      - Sommaire: linux-handbook/summary.md
      - 1 - Installation de Linux et des logiciels: linux-handbook/01-installation-de-linux-et-des-logiciels.md
      - 2 - Démarrage de Linux et gestion des services: linux-handbook/02-demarrage-de-linux-et-gestion-des-services.md
      - 3 - Systèmes de fichiers et périphériques: linux-handbook/03-systemes-de-fichiers-et-periphériques.md
      - 4 - Noyau Linux: linux-handbook/04-noyaux-linux.md
      - 5 - Shell et commandes GNU: linux-handbook/05-shell-et-commandes-gnu.md
      - 6 - Maintenance du système: linux-handbook/06-maintenance-du-système.md
      - 7 - Planification des ressources: linux-handbook/07-planification-des-ressources.md
      - 8 - Tâches d'administration: 
          - Service cron et crontab: linux-handbook/08-taches-d-administration/service-cron-et-crontab.md
      - 9 - Réseau: linux-handbook/09-reseau.md
      - 10 - Sécurité du système: linux-handbook/10-securite-du-systeme.md
      - 11 - Interfaces graphiques: linux-handbook/11-interfaces-graphiques.md
      - 12 - Virtualisation - Machines virtuelles, containers et cloud: linux-handbook/12-virtualisation-machines-virtuelles-containers-et-cloud.md
      - 13 - Services Linux: linux-handbook/13-services-linux.md
      - Références: linux-handbook/references.md  
